# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiaUdSMktmczJVSy84akZaQzlqTnNyZHo2eTEzSkJBYmF3QlZ4dlBSU1dWaz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiQUNMU2tpbVRNU1IwR0psc2dxSzRrK0JsZXZwUFJkWmcrQmwrRm12M1cxTT0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJHSDdhMUt3clE2YVlzUVRxN1l6d3VzTnkraXZpcHM0T0paZzVUbnN3Y1ZRPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJ6WFNGd2JBampCcWpXcWkzRmhORkREaHlndTA0ZXh0V1pJMTlsK3Y3cEY0PSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6Ik9LU3R3d1lJaE9GcjQrN05GWVExUHNMb21Ra3ZxUHo4YmFKdjB2c0dWMnc9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkhkcE5tYjZoZnFudEd3b1MvWHZGWVk4bUJsbk5taWVmQ2YwRFQ0OWV6Z3c9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiK1BRbXhMbzZWTkltdG1sQmlhbmo0cERQSVUyQzVmVGx5OXlLMHhoQ2ltOD0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiOVBIR3RLRDd1SUh4eTduUDNiWXVZRGxUWW1CdkJhQWEvNUlPbWZzdWZRWT0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IjB0MFZkZml5V20vQ2dOVFBhWGJRdm5ydzRUR2l5SEIvVFBVSThXSlVjU1M3MUE4QUlORGVReVFCVzlvMURIbnJRMWY5ZDYydVE5elFHNmFsbEV2ZGpnPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6ODcsImFkdlNlY3JldEtleSI6IjZ6NmRIVFF6dXBuU0xSZXl1QzVkalJDaThGa3BJc0JDSlJkMnBwdUNtRDQ9IiwicHJvY2Vzc2VkSGlzdG9yeU1lc3NhZ2VzIjpbXSwibmV4dFByZUtleUlkIjozMSwiZmlyc3RVbnVwbG9hZGVkUHJlS2V5SWQiOjMxLCJhY2NvdW50U3luY0NvdW50ZXIiOjAsImFjY291bnRTZXR0aW5ncyI6eyJ1bmFyY2hpdmVDaGF0cyI6ZmFsc2V9LCJkZXZpY2VJZCI6IktjRnoyYXlZVHVDM1NpUk5zb1JQcGciLCJwaG9uZUlkIjoiZjZmMDk0ZWMtNDRkYy00NDVmLWFhYWQtM2U3YmU1MmM0NDIwIiwiaWRlbnRpdHlJZCI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6InBuQjUwdGc5NHhmTmt4QzEwRXNLdGxyNTRUZz0ifSwicmVnaXN0ZXJlZCI6dHJ1ZSwiYmFja3VwVG9rZW4iOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJiaVh0RlFnYTZLM3BzYm1rMkJ4bGdSRE5ic289In0sInJlZ2lzdHJhdGlvbiI6e30sInBhaXJpbmdDb2RlIjoiRDU2TDhBOFQiLCJtZSI6eyJpZCI6IjI1NDc5MDE5NDIzNjo1OUBzLndoYXRzYXBwLm5ldCJ9LCJhY2NvdW50Ijp7ImRldGFpbHMiOiJDT3ZnMDRBSEVQbjBtN1FHR0FJZ0FDZ0EiLCJhY2NvdW50U2lnbmF0dXJlS2V5IjoiVzR4bnNuMGdPS0Fya3hVUytaUDdwWjMxcytFU3U3S01ZRlMrc1lHbCtUOD0iLCJhY2NvdW50U2lnbmF0dXJlIjoiZm02bC85UHg4R2o5Y1FJMi9xcFo1Ylp2dHgxY3Jpa085azk5YW5LbGw4ZjgwVi9YNmNrazBGSW1NaHZmdTc2VzVkZTBzRHk4aFhWNXk3SE44RFBQRFE9PSIsImRldmljZVNpZ25hdHVyZSI6IlpiUE5tOXRoVXZpaFFocjlyTlF1SFhUV3dMdWR0a09lZzdXZ0JvVW52ZjJ5cXlrVHVmZnhkSFlQZ2l6elVMREtLVXlXQ3lTbGJpQkxPYWgrWjVXNWdBPT0ifSwic2lnbmFsSWRlbnRpdGllcyI6W3siaWRlbnRpZmllciI6eyJuYW1lIjoiMjU0NzkwMTk0MjM2OjU5QHMud2hhdHNhcHAubmV0IiwiZGV2aWNlSWQiOjB9LCJpZGVudGlmaWVyS2V5Ijp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiQlZ1TVo3SjlJRGlnSzVNVkV2bVQrNldkOWJQaEVydXlqR0JVdnJHQnBmay8ifX1dLCJwbGF0Zm9ybSI6ImFuZHJvaWQiLCJsYXN0QWNjb3VudFN5bmNUaW1lc3RhbXAiOjE3MjAxMjE5ODl9
